In [2]:
import pandas as pd
import ast

# Load data
movies = pd.read_csv("movies.csv")
credits = pd.read_csv("credits.csv")

# Merge on title
movies = movies.merge(credits, on='title')

# Keep only the needed columns
movies = movies[['genres', 'id', 'keywords', 'title', 'overview', 'cast', 'crew']]

# Convert cast to string format if needed
def convert_cast(text):
    try:
        return ast.literal_eval(text)
    except:
        return []

movies['cast'] = movies['cast'].apply(convert_cast)

# Extract only Director from crew column
def fetch_director(text):
    try:
        crew_list = ast.literal_eval(text)
        for member in crew_list:
            if member['job'] == 'Director':
                return member['name']
    except:
        return None

movies['crew'] = movies['crew'].apply(fetch_director)

# Show cleaned dataframe
movies.head()

,genres,id,keywords,title,overview,cast,crew
0,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",Avatar,"In the 22nd century, a paraplegic Marine is di...","[{'cast_id': 242, 'character': 'Jake Sully', '...",James Cameron
1,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{'cast_id': 4, 'character': 'Captain Jack Spa...",Gore Verbinski
2,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",Spectre,A cryptic message from Bond’s past sends him o...,"[{'cast_id': 1, 'character': 'James Bond', 'cr...",Sam Mendes
3,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",The Dark Knight Rises,Following the death of District Attorney Harve...,"[{'cast_id': 2, 'character': 'Bruce Wayne / Ba...",Christopher Nolan
4,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",John Carter,"John Carter is a war-weary, former military ca...","[{'cast_id': 5, 'character': 'John Carter', 'c...",Andrew Stanton

In [3]:
movies["crew"]

0           James Cameron
1          Gore Verbinski
2              Sam Mendes
3       Christopher Nolan
4          Andrew Stanton
              ...
4804     Robert Rodriguez
4805         Edward Burns
4806          Scott Smith
4807          Daniel Hsia
4808     Brian Herzlinger
Name: crew, Length: 4809, dtype: object

In [4]:
import ast  # for literal_eval

def convert(obj):
    L = []
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [5]:
movies['genres'] = movies['genres'].apply(convert)

In [6]:
movies['keywords'] = movies['keywords'].apply(convert)

In [10]:
def convert2(obj):
    L = []
    counter = 0
    for i in obj:  # Removed ast.literal_eval
        if counter <= 2:
            L.append(i['name'])
            counter += 1
        else:
            break
    return L

In [11]:
movies['cast'] = movies['cast'].apply(convert2)

In [12]:
movies.head()

,genres,id,keywords,title,overview,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[culture clash, future, space war, space colon...",Avatar,"In the 22nd century, a paraplegic Marine is di...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",James Cameron
1,"[Adventure, Fantasy, Action]",285,"[ocean, drug abuse, exotic island, east india ...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Johnny Depp, Orlando Bloom, Keira Knightley]",Gore Verbinski
2,"[Action, Adventure, Crime]",206647,"[spy, based on novel, secret agent, sequel, mi...",Spectre,A cryptic message from Bond’s past sends him o...,"[Daniel Craig, Christoph Waltz, Léa Seydoux]",Sam Mendes
3,"[Action, Crime, Drama, Thriller]",49026,"[dc comics, crime fighter, terrorist, secret i...",The Dark Knight Rises,Following the death of District Attorney Harve...,"[Christian Bale, Michael Caine, Gary Oldman]",Christopher Nolan
4,"[Action, Adventure, Science Fiction]",49529,"[based on novel, mars, medallion, space travel...",John Carter,"John Carter is a war-weary, former military ca...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",Andrew Stanton